export default{
     search: require("../assets/search.png"),
     cart: require("../assets/cart.png"),
     back : require("../assets/back.png"),
     plus :require("../assets/plus.png"),
     minus : require("../assets/minus.png"),
     order : require("../assets/order.png"),
     success : require("../assets/Success.png"),
     addCart : require("../assets/add_cart.png"),
     notSearch : require("../assets/notSearch.png"),
     profile: require("../assets/profile.png"),
     next : require("../assets/next.png"),
     email: require("../assets/email.png"),
     eye : require("../assets/eye.png"),
     phone: require("../assets/phone.png"),
     logout : require("../assets/logout.png"),
     name : require("../assets/name.png"),
     camera : require("../assets/camera.png"),
     order : require("../assets/order.png"),
}
